query AlbumsShow($id: ID!) {
  album(id: $id) {
    id
    albumTitle
    year
    shouldListenAlbum
    albumCovers {
      url
    }
    reviews {
      reviewer
      rate
    }
    artist {
      name
    }
    tracks {
      id
      track
      name
      side
      mustHearTracks
    }
  }
}
